MfBfDriver\ORM\Core\BlogComment:
    type: entity
    table: blog_comment
    indexes:
        blog_comment_post_id_idx:
            columns:
                - post_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        author:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        post:
            targetEntity: MfBfDriver\ORM\Core\BlogPost
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                post_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
